const SET_MSGTIP = 'SET_MSGTIP'
const HIDE_MSGTIP = 'HIDE_MSGTIP'
const SHOW_LOADING = "SHOW_LOADING"
const HIDE_LOADING = "HIDE_LOADING"
export {
	
	SET_MSGTIP,
	HIDE_MSGTIP,
	SHOW_LOADING,
	HIDE_LOADING
}
